// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Entry {
    "id": string;
    "goalId": string;
    "date": string;
    "timestamp": string;
    "value": any;
    "note"?: string;

    /** Creates a new Entry instance. */
    constructor($$source: Partial<Entry> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("goalId" in $$source)) {
            this["goalId"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("timestamp" in $$source)) {
            this["timestamp"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Entry instance from a string or object.
     */
    static createFrom($$source: any = {}): Entry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Entry($$parsedSource as Partial<Entry>);
    }
}

export class Goal {
    "id": string;
    "name": string;
    "description"?: string;
    "type": GoalType;
    "createdAt": string;
    "config": { [_: string]: any };
    "milestones": Milestone[];

    /** Creates a new Goal instance. */
    constructor($$source: Partial<Goal> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = GoalType.$zero;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }
        if (!("config" in $$source)) {
            this["config"] = {};
        }
        if (!("milestones" in $$source)) {
            this["milestones"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Goal instance from a string or object.
     */
    static createFrom($$source: any = {}): Goal {
        const $$createField5_0 = $$createType0;
        const $$createField6_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField5_0($$parsedSource["config"]);
        }
        if ("milestones" in $$parsedSource) {
            $$parsedSource["milestones"] = $$createField6_0($$parsedSource["milestones"]);
        }
        return new Goal($$parsedSource as Partial<Goal>);
    }
}

export enum GoalType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    GoalTypeNumeric = "numeric",
    GoalTypeAdherence = "adherence",
    GoalTypeFrequency = "frequency",
    GoalTypeDuration = "duration",
};

export class Milestone {
    "id": string;
    "value": number;
    "label": string;
    "achieved"?: boolean | null;
    "achievedDate"?: string;

    /** Creates a new Milestone instance. */
    constructor($$source: Partial<Milestone> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Milestone instance from a string or object.
     */
    static createFrom($$source: any = {}): Milestone {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Milestone($$parsedSource as Partial<Milestone>);
    }
}

export class SubTask {
    "id": string;
    "text": string;
    "completed": boolean;

    /** Creates a new SubTask instance. */
    constructor($$source: Partial<SubTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("completed" in $$source)) {
            this["completed"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SubTask instance from a string or object.
     */
    static createFrom($$source: any = {}): SubTask {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SubTask($$parsedSource as Partial<SubTask>);
    }
}

export class Tag {
    "id": string;
    "name": string;
    "color": string;

    /** Creates a new Tag instance. */
    constructor($$source: Partial<Tag> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("color" in $$source)) {
            this["color"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Tag instance from a string or object.
     */
    static createFrom($$source: any = {}): Tag {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Tag($$parsedSource as Partial<Tag>);
    }
}

export class Todo {
    "id": string;
    "date": string;
    "text": string;
    "completed": boolean;
    "createdAt": string;
    "tagIds"?: string[];
    "order"?: number | null;
    "subTasks"?: SubTask[];

    /** Creates a new Todo instance. */
    constructor($$source: Partial<Todo> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = "";
        }
        if (!("text" in $$source)) {
            this["text"] = "";
        }
        if (!("completed" in $$source)) {
            this["completed"] = false;
        }
        if (!("createdAt" in $$source)) {
            this["createdAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Todo instance from a string or object.
     */
    static createFrom($$source: any = {}): Todo {
        const $$createField5_0 = $$createType3;
        const $$createField7_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tagIds" in $$parsedSource) {
            $$parsedSource["tagIds"] = $$createField5_0($$parsedSource["tagIds"]);
        }
        if ("subTasks" in $$parsedSource) {
            $$parsedSource["subTasks"] = $$createField7_0($$parsedSource["subTasks"]);
        }
        return new Todo($$parsedSource as Partial<Todo>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = Milestone.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $Create.Array($Create.Any);
const $$createType4 = SubTask.createFrom;
const $$createType5 = $Create.Array($$createType4);
