// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";

export function CreateEntry(entry: models$0.Entry): $CancellablePromise<models$0.Entry> {
    return $Call.ByID(2729518327, entry).then(($result: any) => {
        return $$createType0($result);
    });
}

export function CreateGoal(goal: models$0.Goal): $CancellablePromise<models$0.Goal> {
    return $Call.ByID(2893429426, goal).then(($result: any) => {
        return $$createType1($result);
    });
}

export function CreateTag(tag: models$0.Tag): $CancellablePromise<models$0.Tag> {
    return $Call.ByID(563666911, tag).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CreateTodo(todo: models$0.Todo): $CancellablePromise<models$0.Todo> {
    return $Call.ByID(1330953713, todo).then(($result: any) => {
        return $$createType3($result);
    });
}

export function DataDir(): $CancellablePromise<string> {
    return $Call.ByID(2758281320);
}

export function DeleteEntry(id: string): $CancellablePromise<void> {
    return $Call.ByID(1403220502, id);
}

export function DeleteGoal(id: string): $CancellablePromise<void> {
    return $Call.ByID(68983809, id);
}

export function DeleteTag(id: string): $CancellablePromise<void> {
    return $Call.ByID(3028760942, id);
}

export function DeleteTodo(id: string): $CancellablePromise<void> {
    return $Call.ByID(1565732142, id);
}

export function GetEntry(id: string): $CancellablePromise<models$0.Entry | null> {
    return $Call.ByID(2732711701, id).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetGoal(id: string): $CancellablePromise<models$0.Goal | null> {
    return $Call.ByID(1487334708, id).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ListEntries(goalID: string): $CancellablePromise<models$0.Entry[]> {
    return $Call.ByID(3404728419, goalID).then(($result: any) => {
        return $$createType6($result);
    });
}

export function ListGoals(): $CancellablePromise<models$0.Goal[]> {
    return $Call.ByID(2525604559).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListTags(): $CancellablePromise<models$0.Tag[]> {
    return $Call.ByID(674063568).then(($result: any) => {
        return $$createType8($result);
    });
}

export function ListTodos(): $CancellablePromise<models$0.Todo[]> {
    return $Call.ByID(958678106).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ReorderTodos(orderedIDs: string[]): $CancellablePromise<void> {
    return $Call.ByID(43653389, orderedIDs);
}

export function UpdateEntry(entry: models$0.Entry): $CancellablePromise<models$0.Entry> {
    return $Call.ByID(3792001900, entry).then(($result: any) => {
        return $$createType0($result);
    });
}

export function UpdateGoal(goal: models$0.Goal): $CancellablePromise<models$0.Goal> {
    return $Call.ByID(4068567195, goal).then(($result: any) => {
        return $$createType1($result);
    });
}

export function UpdateTag(tag: models$0.Tag): $CancellablePromise<models$0.Tag> {
    return $Call.ByID(2070746712, tag).then(($result: any) => {
        return $$createType2($result);
    });
}

export function UpdateTodo(todo: models$0.Todo): $CancellablePromise<models$0.Todo> {
    return $Call.ByID(289284688, todo).then(($result: any) => {
        return $$createType3($result);
    });
}

// Private type creation functions
const $$createType0 = models$0.Entry.createFrom;
const $$createType1 = models$0.Goal.createFrom;
const $$createType2 = models$0.Tag.createFrom;
const $$createType3 = models$0.Todo.createFrom;
const $$createType4 = $Create.Nullable($$createType0);
const $$createType5 = $Create.Nullable($$createType1);
const $$createType6 = $Create.Array($$createType0);
const $$createType7 = $Create.Array($$createType1);
const $$createType8 = $Create.Array($$createType2);
const $$createType9 = $Create.Array($$createType3);
